/*Spaces*//*Identifier*//*Punctuator*/using/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/System/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
/*Spaces*//*Identifier*//*Punctuator*/using/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/System/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Collections/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Generic/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
/*Spaces*//*Identifier*//*Punctuator*/using/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/System/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Text/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
/*Spaces*//*Identifier*//*Punctuator*/using/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/System/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Threading/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Tasks/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
/*Spaces*//*Identifier*//*Punctuator*/using/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/System/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Text/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/RegularExpressions/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
/*Spaces*//*Identifier*//*Punctuator*/using/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/System/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/IO/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
/*Spaces*//*Identifier*//*Punctuator*/using/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/System/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Linq/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/

/*Spaces*//*Identifier*//*Punctuator*/namespace/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Lab2/*Spaces*//*Spaces*//*Punctuator*/
/*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
    /*Spaces*//*Identifier*//*Punctuator*/public/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/enum/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/TokenType/*Spaces*//*Spaces*//*Punctuator*/
    /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/Identifier/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/Spaces/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/Punctuator/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/NumberLiteral/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/StringLiteral/*Spaces*//*Spaces*//*Punctuator*/
    /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
    /*Spaces*//*Identifier*//*Punctuator*/public/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/class/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Token/*Spaces*//*Spaces*//*Punctuator*/
    /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/public/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/readonly/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/TokenType/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Type/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/public/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/readonly/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Lexeme/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/public/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Token/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/TokenType/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/type/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/lexeme/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/Type/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/type/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/Lexeme/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/lexeme/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
    /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
    /*Spaces*//*Identifier*//*Punctuator*/class/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Program/*Spaces*//*Spaces*//*Punctuator*/
    /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/public/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/static/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/IEnumerable/*Spaces*//*Punctuator*//*Punctuator*/</*Spaces*//*Identifier*//*Punctuator*/Token/*Spaces*//*Punctuator*//*Punctuator*/>/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/GetTokens/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/text/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/var/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/regex/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Regex/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"
                (?<StringLiteral>@""(""""|[^""])*"") |
                (?<Identifier>[a-zA-Z][a-zA-Z0-9]*) |
                (?<Punctuator>=>|\+\+|!=|[<>{}[\]()=+\.,:;""\\)@]) |
                (?<NumberLiteral>[0-9]+) |
                (?<Spaces>[ \n\r\t]+|/\*.*?\*/)
                "/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/RegexOptions/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/IgnorePatternWhitespace/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/int/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/index/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*NumberLiteral*//*Punctuator*/0/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/foreach/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/Match/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/in/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/regex/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Matches/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/text/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/var/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/lexeme/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Value/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/if/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Index/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/!=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/index/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                    /*Spaces*//*Identifier*//*Punctuator*/throw/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Exception/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"Error: "/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/index/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/index/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Index/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Length/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/if/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Groups/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*StringLiteral*//*Punctuator*/@"Identifier"/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Success/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                    /*Spaces*//*Identifier*//*Punctuator*/yield/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/return/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Token/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/TokenType/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Identifier/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/lexeme/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/else/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/if/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Groups/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*StringLiteral*//*Punctuator*/@"Spaces"/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Success/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                    /*Spaces*//*Identifier*//*Punctuator*/yield/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/return/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Token/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/TokenType/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Spaces/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/lexeme/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/else/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/if/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Groups/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*StringLiteral*//*Punctuator*/@"Punctuator"/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Success/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                    /*Spaces*//*Identifier*//*Punctuator*/yield/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/return/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Token/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/TokenType/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Punctuator/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/lexeme/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/else/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/if/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Groups/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*StringLiteral*//*Punctuator*/@"NumberLiteral"/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Success/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                    /*Spaces*//*Identifier*//*Punctuator*/yield/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/return/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Token/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/TokenType/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/NumberLiteral/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/lexeme/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/else/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/if/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Groups/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*StringLiteral*//*Punctuator*/@"StringLiteral"/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Success/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                    /*Spaces*//*Identifier*//*Punctuator*/yield/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/return/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Token/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/TokenType/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/StringLiteral/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/lexeme/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/if/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/text/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Length/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/!=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/index/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/throw/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Exception/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"Error: "/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/index/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/static/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/void/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Main/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/args/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/input/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/File/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/ReadAllText/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"../../../Lab2/Program.cs"/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Encoding/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Default/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/var/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/str/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/StringBuilder/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/foreach/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/var/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/token/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/in/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/GetTokens/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/input/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/switch/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*NumberLiteral*//*Punctuator*/1/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                    /*Spaces*//*Identifier*//*Punctuator*/case/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*NumberLiteral*//*Punctuator*/0/*Spaces*//*Punctuator*//*Punctuator*/:/*Spaces*//*Spaces*//*Punctuator*/
                        /*Spaces*//*Identifier*//*Punctuator*/str/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Append/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Punctuator*//*Punctuator*/"/*Spaces*//*Spaces*//*Punctuator*//*" + token.Type.ToString() + "*//*Spaces*//*Punctuator*//*Punctuator*/"/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/token/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Lexeme/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                        /*Spaces*//*Identifier*//*Punctuator*/break/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                    /*Spaces*//*Identifier*//*Punctuator*/case/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*NumberLiteral*//*Punctuator*/1/*Spaces*//*Punctuator*//*Punctuator*/:/*Spaces*//*Spaces*//*Punctuator*/
                        /*Spaces*//*Identifier*//*Punctuator*/str/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Append/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/token/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Lexeme/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Append/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@" "/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                        /*Spaces*//*Identifier*//*Punctuator*/break/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                    /*Spaces*//*Identifier*//*Punctuator*/case/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*NumberLiteral*//*Punctuator*/2/*Spaces*//*Punctuator*//*Punctuator*/:/*Spaces*//*Spaces*//*Punctuator*/
                        /*Spaces*//*Identifier*//*Punctuator*/str/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Append/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/token/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Lexeme/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                        /*Spaces*//*Identifier*//*Punctuator*/break/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/output/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/str/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/ToString/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/File/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/WriteAllText/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"../../../Lab2Out/Program.cs"/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/output/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Encoding/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Default/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/static/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/s/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=>/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@""""/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/s/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Replace/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@""""/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@""""""/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@""""/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Identifier*//*Punctuator*/static/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/void/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Text/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/args/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/int/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/k/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*NumberLiteral*//*Punctuator*/0/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/var/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/s/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/File/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/ReadAllText/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"..\..\Regex.txt"/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/var/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/p/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/File/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/ReadAllText/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"..\..\Text.txt"/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/List/*Spaces*//*Punctuator*//*Punctuator*/</*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Punctuator*//*Punctuator*/>/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/output/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/List/*Spaces*//*Punctuator*//*Punctuator*/</*Spaces*//*Identifier*//*Punctuator*/string/*Spaces*//*Punctuator*//*Punctuator*/>/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/output/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Add/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"Номер"/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Spaces*//*Punctuator*/
                     /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"Группа 1"/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Spaces*//*Punctuator*/
                     /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"Группа 2"/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Spaces*//*Punctuator*/
                     /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"Группа 3"/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Spaces*//*Punctuator*/
                     /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"Группа 4"/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Spaces*//*Punctuator*/
                     /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"Группа 5"/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/var/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/rx/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/=/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/new/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Regex/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/s/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/foreach/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/Match/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/in/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/rx/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Matches/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/p/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Punctuator*//*Punctuator*/{/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/k/*Spaces*//*Punctuator*//*Punctuator*/++/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
                /*Spaces*//*Identifier*//*Punctuator*/output/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Add/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"строка "/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/k/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/
                           /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Groups/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*NumberLiteral*//*Punctuator*/1/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Value/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/
                           /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Groups/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*NumberLiteral*//*Punctuator*/2/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Value/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/
                           /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Groups/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*NumberLiteral*//*Punctuator*/3/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Value/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/
                           /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Groups/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*NumberLiteral*//*Punctuator*/4/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Value/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/
                           /*Spaces*//*Identifier*//*Punctuator*/EscapeCsvValue/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*Identifier*//*Punctuator*/match/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Groups/*Spaces*//*Punctuator*//*Punctuator*/[/*Spaces*//*NumberLiteral*//*Punctuator*/5/*Spaces*//*Punctuator*//*Punctuator*/]/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Value/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Punctuator*//*Punctuator*/+/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*StringLiteral*//*Punctuator*/@";"/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
            /*Spaces*//*Identifier*//*Punctuator*/File/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/WriteAllLines/*Spaces*//*Punctuator*//*Punctuator*/(/*Spaces*//*StringLiteral*//*Punctuator*/@"..\..\Output.csv"/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/output/*Spaces*//*Punctuator*//*Punctuator*/,/*Spaces*//*Spaces*//*Punctuator*/ /*Spaces*//*Identifier*//*Punctuator*/Encoding/*Spaces*//*Punctuator*//*Punctuator*/./*Spaces*//*Identifier*//*Punctuator*/Default/*Spaces*//*Punctuator*//*Punctuator*/)/*Spaces*//*Punctuator*//*Punctuator*/;/*Spaces*//*Spaces*//*Punctuator*/
        /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
    /*Spaces*//*Punctuator*//*Punctuator*/}/*Spaces*//*Spaces*//*Punctuator*/
/*Spaces*//*Punctuator*//*Punctuator*/}